### ISSUE TITLE
Cannot find hash in assets

### ISSUE THREAD

**Issue by konek101** [Flowsqy/ShopChestLangGenerator#2]
I got the hash for pl_pl normal not realms i pasted it in to search in .minecraft/assets and no results im on windows

**Comment by konek101** [comment]
btw you should do like a video tutorial how to configure it like a 5 minute thing

**Comment by Flowsqy** [comment]
Did you launch your game in the desired language at least once ?

**Comment by konek101** [comment]
yes

**Comment by konek101** [comment]
im on 1.19.3 took hash for pl_pl from 1.19.json searched assets and nothing look
![image](https://github.com/Flowsqy/ShopChestLangGenerator/assets/131317299/20b4073f-c661-4e65-84bb-249adc202f4e)
am i doing something wrong?

**Comment by konek101** [comment]
i tried doing english but i have no idea how to do that either

**Comment by Flowsqy** [comment]
Okay, now I understand x). Basically, Windows sucks. First, try opening the json files with an application that indent its content for you. You can do it with your web browser (at least with Firefox) otherwise you will struggle to see the hierarchy of things. And to find the file, don't use the search bar. Sometimes it's not exhaustive (at least on windows 🤡). You need to manually search for it in your asset Minecraft folder. (Note that this folder can be located in another location if you have a different launcher but as you found the index I will assume that you use the default one). In the object assets folder, you need to look at the sub folder named with the two first character of the hash. The file will be in this subfolder. For polish it's in `assets/objects/56/` . Tell if you see it.

**Comment by konek101** [comment]
Well two things i knew it should be in 56 so i search manualy there and it is not there second i got the .json from the jar file in versions then in sublime text edited it in 30 sec for it to be comatible so still unresolved with the file but i got the file in another way btw this is folder 56 
![image](https://github.com/Flowsqy/ShopChestLangGenerator/assets/131317299/e3b58291-d373-4037-91d1-57f1b436ac62)
and no names match with the hash 56103590543b46f90c02c804d7a6de16ffc28eed so i have no idea what is wrong with my thing

**Comment by Flowsqy** [comment]
I will inspect that as soon as possible but rn I'm stuck in another country

**Comment by Flowsqy** [comment]
With a bit of testing, I found out that the hash for the pl_pl language file in 1.19.3 is `b10ce340546812fb03c87f2847416336a0b8bafe`. I did not manage to find a match with your hash in the 1.19.3 index neither in the 1.20.1 one. So it looks like you did not take the good index file at first. I don't use the official minecraft launcher (I use MultiMc instead) so file name for indexes may be different. In my case, `2.json` is for 1.19.3 and `5.json` is for 1.20.1.
